### ISSUE TITLE
Doesn't detect wooting 60he

### ISSUE THREAD

**Issue by ecast040** [ShayBox/WootingProfileSwitcher#7]
Says no keyboard found, compiled using x86 on windows and installed all C and C++ libraries I could find to get it to compile. Is there a file I need to edit for it to recognize the keyboard?

**Comment by BigBrainAFK** [comment]
you just need to replace the dll/source for the Wooting sdk

ill update it later

**Comment by BigBrainAFK** [comment]
should be fixed

**Comment by ecast040** [comment]
Recompiled and it still says keyboard not detected, Did a git pull before re-running 'nmake release32' and then executed from command prompt (none admin) under WootingProfileSwitcher\windows\build\bin\release\x86>WootingProfileSwitcher_x86.exe

**Comment by ecast040** [comment]
I ran git submodule update --recursive
Submodule path 'cJSON': checked out 'b45f48e600671feade0b6bd65d1c69de7899f2be'
Submodule path 'wooting-rgb-sdk': checked out '05bcd47268118d8c901826006e5b3d8ea560db08'

and I still get the same result "Keyboard not connected". I'm building the 32 bit version if that matters. Here's my output from compiling

 Visual Studio> nmake release32

Microsoft (R) Program Maintenance Utility Version 14.34.31937.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "%VCToolsInstallDir%bin\Hostx86\x86\cl.exe" /Fe%DIR_COMP_X86%\WootingProfileSwitcher_x86.exe %DEBUG_FLAG%/O2 /utf-8 /EHsc /D "WIN32_LEAN_AND_MEAN" /D "VC_EXTRALEAN" /I.\include\wooting-rgb-sdk /I..\cJSON ..\src\main.c  ..\src\win_native.c  ..\src\..\cJSON\cJSON.c /link /MACHINE:X86 /NOLOGO /NODEFAULTLIB /SUBSYSTEM:CONSOLE %LINK_DBG% /LIBPATH:.\lib\x86 ucrt.lib vcruntime.lib msvcrt.lib Kernel32.lib User32.lib wooting-rgb-sdk.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

main.c
..\src\main.c(133): warning C4113: 'void (__cdecl *)(int)' differs in parameter lists from 'void (__cdecl *)(void)'
..\src\main.c(167): warning C4133: 'function': incompatible types - from 'FILE *' to 'const char *'
..\src\main.c(357): warning C4090: 'function': different 'const' qualifiers
win_native.c
cJSON.c
Generating Code...
   Creating library .\build\bin\release\x86\WootingProfileSwitcher_x86.lib and object .\build\bin\release\x86\WootingProfileSwitcher_x86.exp
cJSON.obj
main.obj
win_native.obj
        3 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.

**Comment by BigBrainAFK** [comment]
Ok I just noticed the 60HE ARM isn't supported by the RGB SDK yet. Simon is currently working on getting it merged in together with multi device RGB support for multiple Wootings. I will comment again if its merged as I will update the submodule accordingly

**Comment by ecast040** [comment]
Thank you so much! you guys all rock
